import { CountryVisaProfile } from '@/types/visa';

export const DESTINATIONS: CountryVisaProfile[] = [
  {
    countryCode: 'TH',
    countryName: 'Thailand',
    continent: 'Asia',
    defaultCategory: 'visa_free',
    processingTimeDays: { min: 0, max: 0 },
    baseFeeUsd: 0,
    baseFeeInr: 0,
    stayDurationDays: 60,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for at least 6 months from arrival',
      'Confirmed return or onward flight ticket within 60 days',
      'Proof of accommodation (hotel booking or host invitation)',
      'Proof of funds: minimum 20,000 THB (~₹48,000) per person or 40,000 THB per family',
      'Completed arrival card (TM6 when required)',
    ],
    officialPortalUrl: 'https://www.thaievisa.go.th',
    capitalCity: 'Bangkok',
    popularAirports: ['BKK', 'DMK', 'HKT', 'CNX'],
    bestTimeToVisit: 'November to April',
    tagline: 'Tropical beaches, ornate temples, and vibrant street food.',
    coverImage: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 12500,
    fareTrends: [
      { month: 'Jan', fareInr: 14200 },
      { month: 'Feb', fareInr: 13500 },
      { month: 'Mar', fareInr: 12500, isLowest: true },
      { month: 'Apr', fareInr: 15800 },
      { month: 'May', fareInr: 13900 },
      { month: 'Jun', fareInr: 13200 },
      { month: 'Jul', fareInr: 14000 },
      { month: 'Aug', fareInr: 13600 },
      { month: 'Sep', fareInr: 12800 },
      { month: 'Oct', fareInr: 14500 },
      { month: 'Nov', fareInr: 16800 },
      { month: 'Dec', fareInr: 19500 },
    ],
  },
  {
    countryCode: 'MY',
    countryName: 'Malaysia',
    continent: 'Asia',
    defaultCategory: 'visa_free',
    processingTimeDays: { min: 0, max: 0 },
    baseFeeUsd: 0,
    baseFeeInr: 0,
    stayDurationDays: 30,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for at least 6 months',
      'Malaysia Digital Arrival Card (MDAC) submitted within 3 days before arrival',
      'Confirmed return flight ticket',
      'Confirmed hotel reservations',
      'Proof of sufficient funds for duration of stay',
    ],
    officialPortalUrl: 'https://imigresen-online.imi.gov.my/mdac/main',
    capitalCity: 'Kuala Lumpur',
    popularAirports: ['KUL', 'PEN', 'BKI'],
    bestTimeToVisit: 'December to April',
    tagline: 'Futuristic skylines, lush rainforests, and diverse culinary heritage.',
    coverImage: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 13800,
    fareTrends: [
      { month: 'Jan', fareInr: 15400 },
      { month: 'Feb', fareInr: 14600 },
      { month: 'Mar', fareInr: 13800, isLowest: true },
      { month: 'Apr', fareInr: 14900 },
      { month: 'May', fareInr: 15200 },
      { month: 'Jun', fareInr: 16100 },
      { month: 'Jul', fareInr: 15800 },
      { month: 'Aug', fareInr: 14300 },
      { month: 'Sep', fareInr: 13900 },
      { month: 'Oct', fareInr: 15000 },
      { month: 'Nov', fareInr: 16200 },
      { month: 'Dec', fareInr: 18900 },
    ],
  },
  {
    countryCode: 'VN',
    countryName: 'Vietnam',
    continent: 'Asia',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 3, max: 5 },
    baseFeeUsd: 25,
    baseFeeInr: 2150,
    stayDurationDays: 90,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for at least 6 months with 2 blank pages',
      'Digital passport photo (4x6cm, white background, no glasses)',
      'Scanned copy of passport biographical page',
      'Confirmed return/onward flight booking',
      'Entry and exit port selection matches actual route',
    ],
    officialPortalUrl: 'https://evisa.xuatnhapcanh.gov.vn',
    capitalCity: 'Hanoi',
    popularAirports: ['SGN', 'HAN', 'DAD'],
    bestTimeToVisit: 'February to April & August to October',
    tagline: 'Emerald waters in Ha Long Bay, lantern-lit streets in Hoi An, and coffee culture.',
    coverImage: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 14900,
    fareTrends: [
      { month: 'Jan', fareInr: 17200 },
      { month: 'Feb', fareInr: 16400 },
      { month: 'Mar', fareInr: 15100 },
      { month: 'Apr', fareInr: 14900, isLowest: true },
      { month: 'May', fareInr: 15800 },
      { month: 'Jun', fareInr: 16900 },
      { month: 'Jul', fareInr: 17500 },
      { month: 'Aug', fareInr: 16200 },
      { month: 'Sep', fareInr: 15400 },
      { month: 'Oct', fareInr: 16800 },
      { month: 'Nov', fareInr: 17900 },
      { month: 'Dec', fareInr: 21000 },
    ],
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    continent: 'Asia',
    defaultCategory: 'voa',
    processingTimeDays: { min: 0, max: 0 },
    baseFeeUsd: 35,
    baseFeeInr: 3010,
    stayDurationDays: 30,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for at least 6 months',
      'Payment of 500,000 IDR (~$35 USD) for e-VoA or VoA counter',
      'Return or onward flight ticket',
      'Electronic Customs Declaration (e-CD) QR code prior to landing',
      'Bali Tourist Levy voucher (150,000 IDR for Bali visitors)',
    ],
    officialPortalUrl: 'https://evisa.imigrasi.go.id',
    capitalCity: 'Jakarta',
    popularAirports: ['DPS', 'CGK', 'SUB'],
    bestTimeToVisit: 'April to October',
    tagline: 'Volcanic peaks, spiritual sanctuaries, world-class surf, and lush rice terraces.',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 18500,
    fareTrends: [
      { month: 'Jan', fareInr: 21500 },
      { month: 'Feb', fareInr: 20200 },
      { month: 'Mar', fareInr: 19100 },
      { month: 'Apr', fareInr: 18500, isLowest: true },
      { month: 'May', fareInr: 19800 },
      { month: 'Jun', fareInr: 22400 },
      { month: 'Jul', fareInr: 24800 },
      { month: 'Aug', fareInr: 23600 },
      { month: 'Sep', fareInr: 19900 },
      { month: 'Oct', fareInr: 19200 },
      { month: 'Nov', fareInr: 20500 },
      { month: 'Dec', fareInr: 25900 },
    ],
  },
  {
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    continent: 'Asia',
    defaultCategory: 'visa_free',
    processingTimeDays: { min: 0, max: 0 },
    baseFeeUsd: 0,
    baseFeeInr: 0,
    stayDurationDays: 30,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for 6 months from entry',
      'Sri Lanka ETA registration prior to travel (fee waived for Indian nationals)',
      'Confirmed return ticket',
      'Proof of sufficient travel funds',
    ],
    officialPortalUrl: 'https://www.eta.gov.lk',
    capitalCity: 'Colombo',
    popularAirports: ['CMB'],
    bestTimeToVisit: 'December to April for West/South; May to September for East',
    tagline: 'Golden coastlines, misty tea hills, ancient citadels, and wildlife safaris.',
    coverImage: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 9800,
    fareTrends: [
      { month: 'Jan', fareInr: 11200 },
      { month: 'Feb', fareInr: 10500 },
      { month: 'Mar', fareInr: 9800, isLowest: true },
      { month: 'Apr', fareInr: 11000 },
      { month: 'May', fareInr: 10400 },
      { month: 'Jun', fareInr: 10100 },
      { month: 'Jul', fareInr: 11800 },
      { month: 'Aug', fareInr: 11500 },
      { month: 'Sep', fareInr: 9900 },
      { month: 'Oct', fareInr: 10600 },
      { month: 'Nov', fareInr: 12000 },
      { month: 'Dec', fareInr: 14500 },
    ],
  },
  {
    countryCode: 'MV',
    countryName: 'Maldives',
    continent: 'Asia',
    defaultCategory: 'voa',
    processingTimeDays: { min: 0, max: 0 },
    baseFeeUsd: 0,
    baseFeeInr: 0,
    stayDurationDays: 30,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for at least 1 month from arrival date',
      'Pre-paid confirmed resort / guesthouse booking voucher',
      'Confirmed onward/return air ticket',
      'Imuga Traveler Declaration submitted within 96 hours prior to arrival',
      'Proof of sufficient funds ($100 + $50 per day of stay)',
    ],
    officialPortalUrl: 'https://imuga.immigration.gov.mv',
    capitalCity: 'Malé',
    popularAirports: ['MLE'],
    bestTimeToVisit: 'November to April',
    tagline: 'Overwater villas, crystalline lagoons, and vibrant coral reefs.',
    coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 14200,
    fareTrends: [
      { month: 'Jan', fareInr: 17800 },
      { month: 'Feb', fareInr: 16500 },
      { month: 'Mar', fareInr: 15200 },
      { month: 'Apr', fareInr: 14200, isLowest: true },
      { month: 'May', fareInr: 14800 },
      { month: 'Jun', fareInr: 14500 },
      { month: 'Jul', fareInr: 15600 },
      { month: 'Aug', fareInr: 16100 },
      { month: 'Sep', fareInr: 14900 },
      { month: 'Oct', fareInr: 16000 },
      { month: 'Nov', fareInr: 18200 },
      { month: 'Dec', fareInr: 22800 },
    ],
  },
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    continent: 'Middle East',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 2, max: 4 },
    baseFeeUsd: 90,
    baseFeeInr: 7740,
    stayDurationDays: 30,
    conditionalUpgrades: {
      validUSVisaHolder: {
        eligibleCategory: 'voa',
        allowedStayDays: 14,
        specialFeeUsd: 35,
        conditionNotes: 'Indian nationals with a valid US Visa or Green Card (valid for at least 6 months) receive a 14-day Visa on Arrival at all UAE entry ports for 120 AED (~$35).',
      },
      validSchengenHolder: {
        eligibleCategory: 'voa',
        allowedStayDays: 14,
        specialFeeUsd: 35,
        conditionNotes: 'Indian nationals with a valid Schengen Residence Permit or Visa (min 6 months validity) are eligible for a 14-day Visa on Arrival across UAE airports.',
      },
      validUKVisaHolder: {
        eligibleCategory: 'voa',
        allowedStayDays: 14,
        specialFeeUsd: 35,
        conditionNotes: 'Holders of a valid UK Visa or Residence Card qualify for an instant 14-day Visa on Arrival counter facility at DXB, AUH, and SHJ.',
      },
    },
    requiredDocuments: [
      'Passport valid for at least 6 months',
      'Passport photograph with white background',
      'Confirmed return flight booking',
      'Hotel reservation or proof of host address in UAE',
      'For VoA upgrade: original passport with valid US/UK/Schengen visa stamp',
    ],
    officialPortalUrl: 'https://smartservices.icp.gov.ae',
    capitalCity: 'Abu Dhabi',
    popularAirports: ['DXB', 'AUH', 'SHJ'],
    bestTimeToVisit: 'November to March',
    tagline: 'Architectural marvels, luxury shopping, desert dunes, and world hubs.',
    coverImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 15200,
    fareTrends: [
      { month: 'Jan', fareInr: 17500 },
      { month: 'Feb', fareInr: 16800 },
      { month: 'Mar', fareInr: 15900 },
      { month: 'Apr', fareInr: 15200, isLowest: true },
      { month: 'May', fareInr: 15600 },
      { month: 'Jun', fareInr: 16200 },
      { month: 'Jul', fareInr: 16900 },
      { month: 'Aug', fareInr: 16500 },
      { month: 'Sep', fareInr: 15400 },
      { month: 'Oct', fareInr: 16800 },
      { month: 'Nov', fareInr: 18500 },
      { month: 'Dec', fareInr: 23200 },
    ],
  },
  {
    countryCode: 'TR',
    countryName: 'Turkey',
    continent: 'Europe',
    defaultCategory: 'sticker_required',
    processingTimeDays: { min: 10, max: 15 },
    baseFeeUsd: 180,
    baseFeeInr: 15480,
    stayDurationDays: 30,
    conditionalUpgrades: {
      validUSVisaHolder: {
        eligibleCategory: 'evisa',
        allowedStayDays: 30,
        specialFeeUsd: 50,
        conditionNotes: 'Indian citizens holding a valid US Visa or Green Card can apply for an instant single-entry eVisa (valid 180 days, 30 days stay) online for ~$50.',
      },
      validSchengenHolder: {
        eligibleCategory: 'evisa',
        allowedStayDays: 30,
        specialFeeUsd: 50,
        conditionNotes: 'Valid Schengen Visa or Residence Permit holders can obtain an instant eVisa online via the official Turkish eVisa portal within 5 minutes.',
      },
      validUKVisaHolder: {
        eligibleCategory: 'evisa',
        allowedStayDays: 30,
        specialFeeUsd: 50,
        conditionNotes: 'Valid UK Visa or Residence Permit holders qualify for the electronic Turkish eVisa portal without visiting the VFS visa center.',
      },
    },
    requiredDocuments: [
      'Standard: Extensive financial dossiers, 3-year ITR, 6-month bank statements, VFS appointment',
      'eVisa Upgraded: Passport valid for 6 months, valid US/Schengen/UK visa stamp, return ticket on supported carriers',
      'Hotel reservation confirmation',
      'Proof of minimum $50 per day for duration of stay',
    ],
    officialPortalUrl: 'https://www.evisa.gov.tr',
    capitalCity: 'Ankara',
    popularAirports: ['IST', 'SAW', 'AYT'],
    bestTimeToVisit: 'April to May & September to November',
    tagline: 'Where East meets West: Ottoman palaces, fairy chimneys in Cappadocia, and Bosphorus cruises.',
    coverImage: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 28900,
    fareTrends: [
      { month: 'Jan', fareInr: 32000 },
      { month: 'Feb', fareInr: 30500 },
      { month: 'Mar', fareInr: 28900, isLowest: true },
      { month: 'Apr', fareInr: 33400 },
      { month: 'May', fareInr: 36500 },
      { month: 'Jun', fareInr: 39800 },
      { month: 'Jul', fareInr: 42000 },
      { month: 'Aug', fareInr: 41200 },
      { month: 'Sep', fareInr: 35000 },
      { month: 'Oct', fareInr: 32500 },
      { month: 'Nov', fareInr: 31200 },
      { month: 'Dec', fareInr: 36000 },
    ],
  },
  {
    countryCode: 'GE',
    countryName: 'Georgia',
    continent: 'Europe',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 5, max: 7 },
    baseFeeUsd: 20,
    baseFeeInr: 1720,
    stayDurationDays: 30,
    conditionalUpgrades: {
      validSchengenHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 90,
        specialFeeUsd: 0,
        conditionNotes: 'Holders of valid visas or residence permits from Schengen states, EU, US, UK, or GCC can enter Georgia 100% Visa-Free for up to 90 days in any 180-day period.',
      },
      validUSVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 90,
        specialFeeUsd: 0,
        conditionNotes: 'Valid US Visa or Green Card holders enjoy 90 days visa-free entry directly on arrival with zero government fees.',
      },
      validUKVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 90,
        specialFeeUsd: 0,
        conditionNotes: 'Holders of a valid UK visa enter Georgia visa-free for 90 days upon presenting their passport and physical visa.',
      },
    },
    requiredDocuments: [
      'Valid passport with at least 3 months validity beyond intended stay',
      'Travel health insurance covering the entire duration',
      'Proof of accommodation and return flights',
      'Proof of financial means (bank statement showing min $35/day)',
      'For Visa-Free waiver: physical valid US/UK/Schengen visa in passport',
    ],
    officialPortalUrl: 'https://www.evisa.gov.ge',
    capitalCity: 'Tbilisi',
    popularAirports: ['TBS', 'BUS', 'KUT'],
    bestTimeToVisit: 'May to June & September to October',
    tagline: 'Ancient wine cradles, dramatic Caucasus peaks, and cobblestone sulfur bath quarters.',
    coverImage: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 24500,
    fareTrends: [
      { month: 'Jan', fareInr: 27900 },
      { month: 'Feb', fareInr: 26200 },
      { month: 'Mar', fareInr: 25100 },
      { month: 'Apr', fareInr: 24500, isLowest: true },
      { month: 'May', fareInr: 28400 },
      { month: 'Jun', fareInr: 31200 },
      { month: 'Jul', fareInr: 33500 },
      { month: 'Aug', fareInr: 32000 },
      { month: 'Sep', fareInr: 27800 },
      { month: 'Oct', fareInr: 26500 },
      { month: 'Nov', fareInr: 25800 },
      { month: 'Dec', fareInr: 29900 },
    ],
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    continent: 'Asia',
    defaultCategory: 'visa_free',
    processingTimeDays: { min: 0, max: 0 },
    baseFeeUsd: 0,
    baseFeeInr: 0,
    stayDurationDays: 14,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for at least 3 months beyond entry date',
      'Return or onward flight ticket within 14 days',
      'Hotel reservation confirmation',
      'Travel medical insurance (recommended)',
      'Cumulative stay must not exceed 42 days in any 180-day period',
    ],
    officialPortalUrl: 'https://www.vmp.gov.kz',
    capitalCity: 'Astana',
    popularAirports: ['ALA', 'NQZ'],
    bestTimeToVisit: 'April to May & September to October',
    tagline: 'The dramatic Charyn Canyon, snow-capped Tian Shan, and futuristic architecture.',
    coverImage: 'https://images.unsplash.com/photo-1558588942-930faae5a389?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 17800,
    fareTrends: [
      { month: 'Jan', fareInr: 19800 },
      { month: 'Feb', fareInr: 18900 },
      { month: 'Mar', fareInr: 17800, isLowest: true },
      { month: 'Apr', fareInr: 19200 },
      { month: 'May', fareInr: 21500 },
      { month: 'Jun', fareInr: 23400 },
      { month: 'Jul', fareInr: 24800 },
      { month: 'Aug', fareInr: 23900 },
      { month: 'Sep', fareInr: 20500 },
      { month: 'Oct', fareInr: 19400 },
      { month: 'Nov', fareInr: 18900 },
      { month: 'Dec', fareInr: 22000 },
    ],
  },
  {
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    continent: 'Asia',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 3, max: 3 },
    baseFeeUsd: 26,
    baseFeeInr: 2236,
    stayDurationDays: 30,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for at least 3 months beyond eVisa expiry',
      'Color copy of passport bio page',
      'Accommodation booking details',
      'ASAN Visa electronic printout upon arrival',
    ],
    officialPortalUrl: 'https://evisa.gov.az/en',
    capitalCity: 'Baku',
    popularAirports: ['GYD'],
    bestTimeToVisit: 'April to June & September to October',
    tagline: 'The Land of Fire: Flame Towers, Caspian Sea boulevard, and mud volcanoes.',
    coverImage: 'https://images.unsplash.com/photo-1579606032834-006467389146?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 21900,
    fareTrends: [
      { month: 'Jan', fareInr: 24500 },
      { month: 'Feb', fareInr: 23200 },
      { month: 'Mar', fareInr: 22100 },
      { month: 'Apr', fareInr: 21900, isLowest: true },
      { month: 'May', fareInr: 24800 },
      { month: 'Jun', fareInr: 27500 },
      { month: 'Jul', fareInr: 28900 },
      { month: 'Aug', fareInr: 27200 },
      { month: 'Sep', fareInr: 23900 },
      { month: 'Oct', fareInr: 22800 },
      { month: 'Nov', fareInr: 23400 },
      { month: 'Dec', fareInr: 26800 },
    ],
  },
  {
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    continent: 'Asia',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 2, max: 3 },
    baseFeeUsd: 20,
    baseFeeInr: 1720,
    stayDurationDays: 30,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for at least 3 months beyond visa validity',
      'Electronic photo (35x45mm, white background)',
      'Proof of return flight ticket',
      'Hotel registration slip (retained from each hotel upon checkout)',
    ],
    officialPortalUrl: 'https://e-visa.gov.uz',
    capitalCity: 'Tashkent',
    popularAirports: ['TAS', 'SKD', 'BHK'],
    bestTimeToVisit: 'April to May & September to November',
    tagline: 'Silk Road splendors of Samarkand, Bukhara, and turquoise madrasas.',
    coverImage: 'https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 18900,
    fareTrends: [
      { month: 'Jan', fareInr: 21200 },
      { month: 'Feb', fareInr: 20100 },
      { month: 'Mar', fareInr: 19200 },
      { month: 'Apr', fareInr: 18900, isLowest: true },
      { month: 'May', fareInr: 22400 },
      { month: 'Jun', fareInr: 23900 },
      { month: 'Jul', fareInr: 24500 },
      { month: 'Aug', fareInr: 23800 },
      { month: 'Sep', fareInr: 21000 },
      { month: 'Oct', fareInr: 19800 },
      { month: 'Nov', fareInr: 19500 },
      { month: 'Dec', fareInr: 22900 },
    ],
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    continent: 'Asia',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 3, max: 5 },
    baseFeeUsd: 30,
    baseFeeInr: 2580,
    stayDurationDays: 30,
    conditionalUpgrades: {
      validUSVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 4,
        specialFeeUsd: 0,
        conditionNotes: 'Visa-Free Transit Facility (VFTF): Indian nationals with a valid US, UK, Schengen, Japan, Canada, or Australia visa and a transit flight can enter Singapore for up to 96 hours visa-free.',
      },
      validSchengenHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 4,
        specialFeeUsd: 0,
        conditionNotes: 'Eligible for 96-hour Visa-Free Transit Facility (VFTF) on transit journeys with a confirmed onward ticket to a third country.',
      },
      validUKVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 4,
        specialFeeUsd: 0,
        conditionNotes: 'Eligible for 96-hour Visa-Free Transit Facility (VFTF) when transiting through Changi Airport to/from third countries.',
      },
    },
    requiredDocuments: [
      'Passport valid for at least 6 months',
      'Singapore Arrival Card (SGAC) with electronic health declaration within 3 days prior',
      'Proof of return or onward ticket',
      'For VFTF: valid visa with at least 1 month remaining validity and confirmed onward flight',
    ],
    officialPortalUrl: 'https://eservices.ica.gov.sg',
    capitalCity: 'Singapore',
    popularAirports: ['SIN'],
    bestTimeToVisit: 'Year-round; November to January for festivities',
    tagline: 'Gardens by the Bay, culinary marvels, Marina Bay skyline, and pristine gardens.',
    coverImage: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 16900,
    fareTrends: [
      { month: 'Jan', fareInr: 18900 },
      { month: 'Feb', fareInr: 17800 },
      { month: 'Mar', fareInr: 16900, isLowest: true },
      { month: 'Apr', fareInr: 17500 },
      { month: 'May', fareInr: 18200 },
      { month: 'Jun', fareInr: 20100 },
      { month: 'Jul', fareInr: 19800 },
      { month: 'Aug', fareInr: 18500 },
      { month: 'Sep', fareInr: 17200 },
      { month: 'Oct', fareInr: 18400 },
      { month: 'Nov', fareInr: 19900 },
      { month: 'Dec', fareInr: 24500 },
    ],
  },
  {
    countryCode: 'OM',
    countryName: 'Oman',
    continent: 'Middle East',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 1, max: 3 },
    baseFeeUsd: 52,
    baseFeeInr: 4472,
    stayDurationDays: 30,
    conditionalUpgrades: {
      validUSVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 14,
        specialFeeUsd: 0,
        conditionNotes: 'Indian citizens with a valid US, UK, Schengen, or GCC visa/residence qualify for a 14-day Visa-Free stay or conditional 30-day eVisa (26B).',
      },
      validSchengenHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 14,
        specialFeeUsd: 0,
        conditionNotes: 'Indian passport holders holding valid Schengen visas are exempt from visa fees for stays up to 14 days.',
      },
      validUKVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 14,
        specialFeeUsd: 0,
        conditionNotes: 'Valid UK visa holders can visit Oman visa-free for up to 14 days with hotel bookings and return flight.',
      },
    },
    requiredDocuments: [
      'Passport valid for at least 6 months',
      'Confirmed return ticket and hotel reservation',
      'Travel health insurance covering Oman',
      'For waiver: proof of valid visa/residence of US, UK, Schengen, or Canada',
    ],
    officialPortalUrl: 'https://evisa.rop.gov.om',
    capitalCity: 'Muscat',
    popularAirports: ['MCT', 'SLL'],
    bestTimeToVisit: 'October to April',
    tagline: 'Wadis, dramatic fjords of Musandam, ancient forts, and desert dunes.',
    coverImage: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 14800,
    fareTrends: [
      { month: 'Jan', fareInr: 16900 },
      { month: 'Feb', fareInr: 15800 },
      { month: 'Mar', fareInr: 14800, isLowest: true },
      { month: 'Apr', fareInr: 15400 },
      { month: 'May', fareInr: 15900 },
      { month: 'Jun', fareInr: 16800 },
      { month: 'Jul', fareInr: 17200 },
      { month: 'Aug', fareInr: 16400 },
      { month: 'Sep', fareInr: 15200 },
      { month: 'Oct', fareInr: 16600 },
      { month: 'Nov', fareInr: 17900 },
      { month: 'Dec', fareInr: 21500 },
    ],
  },
  {
    countryCode: 'MU',
    countryName: 'Mauritius',
    continent: 'Africa',
    defaultCategory: 'visa_free',
    processingTimeDays: { min: 0, max: 0 },
    baseFeeUsd: 0,
    baseFeeInr: 0,
    stayDurationDays: 90,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for beyond the date of departure',
      'Confirmed return flight ticket',
      'Proof of confirmed hotel accommodation',
      'Completed Mauritius All-in-One Travel Digital Form prior to boarding',
      'Financial capability: minimum $100 per day of stay',
    ],
    officialPortalUrl: 'https://safetravel.govmu.org',
    capitalCity: 'Port Louis',
    popularAirports: ['MRU'],
    bestTimeToVisit: 'May to December',
    tagline: 'Sapphire waters, white sandy beaches, volcanic monoliths, and Creole gastronomy.',
    coverImage: 'https://images.unsplash.com/photo-1589793907316-f94025b46850?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 33500,
    fareTrends: [
      { month: 'Jan', fareInr: 38900 },
      { month: 'Feb', fareInr: 36500 },
      { month: 'Mar', fareInr: 35000 },
      { month: 'Apr', fareInr: 33500, isLowest: true },
      { month: 'May', fareInr: 34200 },
      { month: 'Jun', fareInr: 35800 },
      { month: 'Jul', fareInr: 39500 },
      { month: 'Aug', fareInr: 38200 },
      { month: 'Sep', fareInr: 34900 },
      { month: 'Oct', fareInr: 36000 },
      { month: 'Nov', fareInr: 38500 },
      { month: 'Dec', fareInr: 44900 },
    ],
  },
  {
    countryCode: 'SC',
    countryName: 'Seychelles',
    continent: 'Africa',
    defaultCategory: 'visa_free',
    processingTimeDays: { min: 0, max: 0 },
    baseFeeUsd: 11,
    baseFeeInr: 946,
    stayDurationDays: 90,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for the period of the intended stay',
      'Seychelles Travel Authorization (TA) applied online (~€10 processing fee)',
      'Confirmed return or onward air ticket',
      'Proof of accommodation bookings',
      'Proof of sufficient funds (minimum $150 per day)',
    ],
    officialPortalUrl: 'https://seychelles.govtas.com',
    capitalCity: 'Victoria',
    popularAirports: ['SEZ'],
    bestTimeToVisit: 'April to May & October to November',
    tagline: 'Granite boulders, giant tortoises, secluded coves, and pristine diving.',
    coverImage: 'https://images.unsplash.com/photo-1589793907316-f94025b46850?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 31500,
    fareTrends: [
      { month: 'Jan', fareInr: 36500 },
      { month: 'Feb', fareInr: 34200 },
      { month: 'Mar', fareInr: 32800 },
      { month: 'Apr', fareInr: 31500, isLowest: true },
      { month: 'May', fareInr: 32900 },
      { month: 'Jun', fareInr: 34500 },
      { month: 'Jul', fareInr: 38200 },
      { month: 'Aug', fareInr: 37900 },
      { month: 'Sep', fareInr: 33400 },
      { month: 'Oct', fareInr: 34800 },
      { month: 'Nov', fareInr: 37200 },
      { month: 'Dec', fareInr: 42500 },
    ],
  },
  {
    countryCode: 'NP',
    countryName: 'Nepal',
    continent: 'Asia',
    defaultCategory: 'visa_free',
    processingTimeDays: { min: 0, max: 0 },
    baseFeeUsd: 0,
    baseFeeInr: 0,
    stayDurationDays: 180,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Original Indian Passport OR original Election Commission Voter ID card',
      '(Aadhaar / PAN card is not accepted for flight travel under treaty rules)',
      'For minors under 18: school ID or birth certificate with parental guardianship',
    ],
    officialPortalUrl: 'https://nepaliport.immigration.gov.np',
    capitalCity: 'Kathmandu',
    popularAirports: ['KTM'],
    bestTimeToVisit: 'October to December & March to May',
    tagline: 'The Himalayas, sacred temples of Pashupatinath, trekking peaks, and tranquil lakes.',
    coverImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 8900,
    fareTrends: [
      { month: 'Jan', fareInr: 10500 },
      { month: 'Feb', fareInr: 9800 },
      { month: 'Mar', fareInr: 8900, isLowest: true },
      { month: 'Apr', fareInr: 9500 },
      { month: 'May', fareInr: 9900 },
      { month: 'Jun', fareInr: 10400 },
      { month: 'Jul', fareInr: 11200 },
      { month: 'Aug', fareInr: 10800 },
      { month: 'Sep', fareInr: 9900 },
      { month: 'Oct', fareInr: 11500 },
      { month: 'Nov', fareInr: 11200 },
      { month: 'Dec', fareInr: 12800 },
    ],
  },
  {
    countryCode: 'BT',
    countryName: 'Bhutan',
    continent: 'Asia',
    defaultCategory: 'visa_free',
    processingTimeDays: { min: 0, max: 0 },
    baseFeeUsd: 15,
    baseFeeInr: 1200,
    stayDurationDays: 14,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Original Indian Passport with minimum 6 months validity OR Voter Identity Card',
      'Entry Permit required (issued at Phuntsholing border or Paro International Airport)',
      'Sustainable Development Fee (SDF) of ₹1,200 per adult per night',
      'Certified Bhutanese tour guide and designated accommodation booking',
      'Travel insurance covering Bhutan',
    ],
    officialPortalUrl: 'https://www.citizenservices.gov.bt/tourism-services',
    capitalCity: 'Thimphu',
    popularAirports: ['PBH'],
    bestTimeToVisit: 'March to May & September to November',
    tagline: 'Tiger’s Nest monastery, gross national happiness, pristine dzongs, and alpine valleys.',
    coverImage: 'https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 16500,
    fareTrends: [
      { month: 'Jan', fareInr: 18500 },
      { month: 'Feb', fareInr: 17800 },
      { month: 'Mar', fareInr: 16500, isLowest: true },
      { month: 'Apr', fareInr: 17900 },
      { month: 'May', fareInr: 18400 },
      { month: 'Jun', fareInr: 19200 },
      { month: 'Jul', fareInr: 19500 },
      { month: 'Aug', fareInr: 19000 },
      { month: 'Sep', fareInr: 17800 },
      { month: 'Oct', fareInr: 19400 },
      { month: 'Nov', fareInr: 18900 },
      { month: 'Dec', fareInr: 20500 },
    ],
  },
  {
    countryCode: 'PH',
    countryName: 'Philippines',
    continent: 'Asia',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 5, max: 8 },
    baseFeeUsd: 50,
    baseFeeInr: 4300,
    stayDurationDays: 14,
    conditionalUpgrades: {
      validUSVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 14,
        specialFeeUsd: 0,
        conditionNotes: 'AJACSSUK Rule: Indian nationals with valid, unexpired US, Schengen, UK, Japan, Australia, Canada, or Singapore visas enter the Philippines Visa-Free for 14 days (extendable up to 21 days).',
      },
      validSchengenHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 14,
        specialFeeUsd: 0,
        conditionNotes: 'Holders of a valid Schengen visa enter Visa-Free for 14 days under the AJACSSUK bilateral visa-free entry program.',
      },
      validUKVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 14,
        specialFeeUsd: 0,
        conditionNotes: 'Holders of a valid UK visa are granted 14 days visa-free entry upon arrival in Manila or Cebu.',
      },
    },
    requiredDocuments: [
      'Passport valid for at least 6 months beyond intended stay',
      'Return or onward flight ticket to third country',
      'eTravel QR code registration within 72 hours prior to arrival',
      'Proof of accommodation in the Philippines',
      'For waiver: passport containing the valid physical US/UK/Schengen visa stamp',
    ],
    officialPortalUrl: 'https://etravel.gov.ph',
    capitalCity: 'Manila',
    popularAirports: ['MNL', 'CEB'],
    bestTimeToVisit: 'November to April',
    tagline: 'Over 7,000 islands, Boracay white sands, Palawan underground rivers, and chocolate hills.',
    coverImage: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 22800,
    fareTrends: [
      { month: 'Jan', fareInr: 25400 },
      { month: 'Feb', fareInr: 24200 },
      { month: 'Mar', fareInr: 22800, isLowest: true },
      { month: 'Apr', fareInr: 24100 },
      { month: 'May', fareInr: 25800 },
      { month: 'Jun', fareInr: 27900 },
      { month: 'Jul', fareInr: 29500 },
      { month: 'Aug', fareInr: 28400 },
      { month: 'Sep', fareInr: 23900 },
      { month: 'Oct', fareInr: 24800 },
      { month: 'Nov', fareInr: 26500 },
      { month: 'Dec', fareInr: 31000 },
    ],
  },
  {
    countryCode: 'AL',
    countryName: 'Albania',
    continent: 'Europe',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 10, max: 15 },
    baseFeeUsd: 55,
    baseFeeInr: 4730,
    stayDurationDays: 90,
    conditionalUpgrades: {
      validSchengenHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 90,
        specialFeeUsd: 0,
        conditionNotes: 'Holders of a valid multiple-entry Schengen, US, or UK visa (must have been used at least once in issuing territory) can enter Albania 100% Visa-Free for up to 90 days.',
      },
      validUSVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 90,
        specialFeeUsd: 0,
        conditionNotes: 'Holders of a valid multiple-entry US visa can enter Albania visa-free for 90 days in a 180-day window.',
      },
      validUKVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 90,
        specialFeeUsd: 0,
        conditionNotes: 'Multiple-entry UK visa holders can visit Albania visa-free for 90 days.',
      },
    },
    requiredDocuments: [
      'Passport valid for at least 3 months beyond departure date',
      'For visa-free entry: multiple-entry US/Schengen/UK visa previously utilized',
      'Return air ticket and confirmed hotel reservation',
      'Proof of financial means of €50 per day of stay',
    ],
    officialPortalUrl: 'https://e-visa.al',
    capitalCity: 'Tirana',
    popularAirports: ['TIA'],
    bestTimeToVisit: 'April to June & September to October',
    tagline: 'The Albanian Riviera, turquoise Ionian coves, Ottoman towns, and Balkan peaks.',
    coverImage: 'https://images.unsplash.com/photo-1590497507963-3b1297e68c0b?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 32900,
    fareTrends: [
      { month: 'Jan', fareInr: 36800 },
      { month: 'Feb', fareInr: 35200 },
      { month: 'Mar', fareInr: 34100 },
      { month: 'Apr', fareInr: 32900, isLowest: true },
      { month: 'May', fareInr: 35800 },
      { month: 'Jun', fareInr: 39500 },
      { month: 'Jul', fareInr: 43200 },
      { month: 'Aug', fareInr: 42000 },
      { month: 'Sep', fareInr: 36500 },
      { month: 'Oct', fareInr: 34200 },
      { month: 'Nov', fareInr: 35100 },
      { month: 'Dec', fareInr: 39900 },
    ],
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    continent: 'Americas',
    defaultCategory: 'sticker_required',
    processingTimeDays: { min: 15, max: 25 },
    baseFeeUsd: 53,
    baseFeeInr: 4558,
    stayDurationDays: 180,
    conditionalUpgrades: {
      validUSVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 180,
        specialFeeUsd: 0,
        conditionNotes: 'Any nationality holding a valid unexpired physical US visa (B1/B2, F1, H1B, etc.) or Green Card can enter Mexico 100% Visa-Free for tourism up to 180 days.',
      },
      validSchengenHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 180,
        specialFeeUsd: 0,
        conditionNotes: 'Holders of a valid unexpired Schengen multiple-entry visa or EU residence permit can enter Mexico visa-free for up to 180 days.',
      },
      validUKVisaHolder: {
        eligibleCategory: 'visa_free',
        allowedStayDays: 180,
        specialFeeUsd: 0,
        conditionNotes: 'Valid UK multiple-entry visa or permanent residence card holders qualify for 180-day visa-free entry.',
      },
    },
    requiredDocuments: [
      'Standard: In-person Mexican Embassy interview, salary slips, 6 months bank statement, biometric appointment',
      'Visa-Free Upgraded: Valid passport and physical valid US/Schengen/UK/Japan/Canada visa stamp',
      'Completed Multiple Migratory Form (FMM) provided by airline or online',
      'Return flight ticket and accommodation proof',
    ],
    officialPortalUrl: 'https://www.inm.gob.mx',
    capitalCity: 'Mexico City',
    popularAirports: ['MEX', 'CUN', 'GDL'],
    bestTimeToVisit: 'December to April',
    tagline: 'Mayan pyramids of Chichen Itza, vibrant Oaxaca cuisine, and turquoise Caribbean waters of Cancun.',
    coverImage: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 58900,
    fareTrends: [
      { month: 'Jan', fareInr: 64500 },
      { month: 'Feb', fareInr: 62000 },
      { month: 'Mar', fareInr: 59900 },
      { month: 'Apr', fareInr: 58900, isLowest: true },
      { month: 'May', fareInr: 61500 },
      { month: 'Jun', fareInr: 66800 },
      { month: 'Jul', fareInr: 71200 },
      { month: 'Aug', fareInr: 69500 },
      { month: 'Sep', fareInr: 61000 },
      { month: 'Oct', fareInr: 62500 },
      { month: 'Nov', fareInr: 65800 },
      { month: 'Dec', fareInr: 78000 },
    ],
  },
  {
    countryCode: 'EG',
    countryName: 'Egypt',
    continent: 'Africa',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 3, max: 7 },
    baseFeeUsd: 25,
    baseFeeInr: 2150,
    stayDurationDays: 30,
    conditionalUpgrades: {
      validUSVisaHolder: {
        eligibleCategory: 'voa',
        allowedStayDays: 30,
        specialFeeUsd: 25,
        conditionNotes: 'Indian citizens with a valid, used US, UK, Schengen, Japan, Canada, or Australia visa can obtain a Visa on Arrival directly at Cairo Airport for $25.',
      },
      validSchengenHolder: {
        eligibleCategory: 'voa',
        allowedStayDays: 30,
        specialFeeUsd: 25,
        conditionNotes: 'Valid Schengen multiple-entry visa holders are eligible for a 30-day Visa on Arrival at Cairo (CAI) and Sharm El Sheikh (SSH).',
      },
      validUKVisaHolder: {
        eligibleCategory: 'voa',
        allowedStayDays: 30,
        specialFeeUsd: 25,
        conditionNotes: 'Valid UK multiple-entry visa holders can obtain Visa on Arrival at Egyptian airports.',
      },
    },
    requiredDocuments: [
      'Passport valid for at least 6 months from arrival',
      'Printed eVisa or approval document',
      'Travel itinerary, hotel booking, and confirmed return flight',
      'For VoA: physical passport with valid US/UK/Schengen sticker',
    ],
    officialPortalUrl: 'https://visa2egypt.gov.eg',
    capitalCity: 'Cairo',
    popularAirports: ['CAI', 'SSH', 'HRG'],
    bestTimeToVisit: 'October to April',
    tagline: 'Great Pyramids of Giza, Nile River feluccas, and Red Sea coral reefs.',
    coverImage: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 24800,
    fareTrends: [
      { month: 'Jan', fareInr: 27500 },
      { month: 'Feb', fareInr: 26200 },
      { month: 'Mar', fareInr: 24800, isLowest: true },
      { month: 'Apr', fareInr: 26500 },
      { month: 'May', fareInr: 27900 },
      { month: 'Jun', fareInr: 29800 },
      { month: 'Jul', fareInr: 31200 },
      { month: 'Aug', fareInr: 30500 },
      { month: 'Sep', fareInr: 27100 },
      { month: 'Oct', fareInr: 28400 },
      { month: 'Nov', fareInr: 29900 },
      { month: 'Dec', fareInr: 34500 },
    ],
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    continent: 'Asia',
    defaultCategory: 'evisa',
    processingTimeDays: { min: 5, max: 7 },
    baseFeeUsd: 22,
    baseFeeInr: 1890,
    stayDurationDays: 90,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for travel period',
      'JAPAN eVISA digital issuance for Indian residents in India & abroad',
      'Flight reservations and daily travel schedule/itinerary',
      'Bank statement showing financial stability for tourist stay',
      'Visit Japan Web QR codes for immigration and customs clearance',
    ],
    officialPortalUrl: 'https://www.evisa.mofa.go.jp',
    capitalCity: 'Tokyo',
    popularAirports: ['HND', 'NRT', 'KIX'],
    bestTimeToVisit: 'March to May (Cherry Blossoms) & September to November (Autumn)',
    tagline: 'Neon metropolis, tranquil Shinto shrines, bullet trains, and Mt. Fuji views.',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 34500,
    fareTrends: [
      { month: 'Jan', fareInr: 38500 },
      { month: 'Feb', fareInr: 36900 },
      { month: 'Mar', fareInr: 34500, isLowest: true },
      { month: 'Apr', fareInr: 45000 },
      { month: 'May', fareInr: 39500 },
      { month: 'Jun', fareInr: 38200 },
      { month: 'Jul', fareInr: 39900 },
      { month: 'Aug', fareInr: 41200 },
      { month: 'Sep', fareInr: 36800 },
      { month: 'Oct', fareInr: 39800 },
      { month: 'Nov', fareInr: 42000 },
      { month: 'Dec', fareInr: 44500 },
    ],
  },
  {
    countryCode: 'FR',
    countryName: 'France (Schengen Area)',
    continent: 'Europe',
    defaultCategory: 'sticker_required',
    processingTimeDays: { min: 15, max: 30 },
    baseFeeUsd: 98,
    baseFeeInr: 8428,
    stayDurationDays: 90,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Passport valid for at least 3 months after departure from Schengen, issued within past 10 years',
      'VFS Global in-person biometric appointment',
      'Confirmed flight itinerary (do not buy non-refundable tickets prior to grant)',
      'Proof of accommodation covering all days in Schengen zone',
      'Travel medical insurance with minimum €30,000 coverage including repatriation',
      'Last 3 years Income Tax Returns (ITR-V)',
      'Last 6 months bank statement with bank stamp/signature',
      'Leave approval letter from employer or business registration',
    ],
    officialPortalUrl: 'https://france-visas.gouv.fr',
    capitalCity: 'Paris',
    popularAirports: ['CDG', 'ORY', 'NCE'],
    bestTimeToVisit: 'April to June & September to November',
    tagline: 'Eiffel Tower, French Riviera, Loire Valley châteaux, and haute couture.',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 36800,
    fareTrends: [
      { month: 'Jan', fareInr: 41200 },
      { month: 'Feb', fareInr: 39500 },
      { month: 'Mar', fareInr: 36800, isLowest: true },
      { month: 'Apr', fareInr: 42500 },
      { month: 'May', fareInr: 48900 },
      { month: 'Jun', fareInr: 54000 },
      { month: 'Jul', fareInr: 58500 },
      { month: 'Aug', fareInr: 56000 },
      { month: 'Sep', fareInr: 44500 },
      { month: 'Oct', fareInr: 40200 },
      { month: 'Nov', fareInr: 39800 },
      { month: 'Dec', fareInr: 47900 },
    ],
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    continent: 'Europe',
    defaultCategory: 'sticker_required',
    processingTimeDays: { min: 15, max: 21 },
    baseFeeUsd: 145,
    baseFeeInr: 12470,
    stayDurationDays: 180,
    conditionalUpgrades: {},
    requiredDocuments: [
      'Standard Visitor Visa application via GOV.UK',
      'VFS appointment for biometrics and passport submission',
      '6 months of bank statements demonstrating genuine funds',
      'Employment letter, payslips, and 3-year ITR forms',
      'Detailed travel itinerary and accommodation details',
    ],
    officialPortalUrl: 'https://www.gov.uk/standard-visitor',
    capitalCity: 'London',
    popularAirports: ['LHR', 'LGW', 'MAN'],
    bestTimeToVisit: 'May to September',
    tagline: 'Historic London landmarks, Scottish Highlands, Cotswolds villages, and theatre.',
    coverImage: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 38900,
    fareTrends: [
      { month: 'Jan', fareInr: 42500 },
      { month: 'Feb', fareInr: 40800 },
      { month: 'Mar', fareInr: 38900, isLowest: true },
      { month: 'Apr', fareInr: 44200 },
      { month: 'May', fareInr: 51000 },
      { month: 'Jun', fareInr: 57500 },
      { month: 'Jul', fareInr: 61800 },
      { month: 'Aug', fareInr: 59000 },
      { month: 'Sep', fareInr: 46500 },
      { month: 'Oct', fareInr: 41800 },
      { month: 'Nov', fareInr: 42900 },
      { month: 'Dec', fareInr: 51200 },
    ],
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    continent: 'Americas',
    defaultCategory: 'sticker_required',
    processingTimeDays: { min: 60, max: 180 },
    baseFeeUsd: 185,
    baseFeeInr: 15910,
    stayDurationDays: 180,
    conditionalUpgrades: {},
    requiredDocuments: [
      'DS-160 Nonimmigrant Visa Application Confirmation',
      'MRV Fee receipt ($185 USD)',
      'Passport valid for at least 6 months beyond intended stay',
      'Two-stage appointment: OFC Biometrics & US Consular in-person interview',
      'Strong ties to India documentation (property, job, family, tax records)',
    ],
    officialPortalUrl: 'https://ceac.state.gov/genniv',
    capitalCity: 'Washington, D.C.',
    popularAirports: ['JFK', 'SFO', 'ORD', 'LAX'],
    bestTimeToVisit: 'Spring (March-May) & Autumn (September-November)',
    tagline: 'From Manhattan skyscrapers to Grand Canyon wonders and California coasts.',
    coverImage: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=900&auto=format&fit=crop&q=80',
    sampleLowFareInr: 59000,
    fareTrends: [
      { month: 'Jan', fareInr: 64800 },
      { month: 'Feb', fareInr: 61500 },
      { month: 'Mar', fareInr: 59000, isLowest: true },
      { month: 'Apr', fareInr: 63500 },
      { month: 'May', fareInr: 72000 },
      { month: 'Jun', fareInr: 81500 },
      { month: 'Jul', fareInr: 86000 },
      { month: 'Aug', fareInr: 79800 },
      { month: 'Sep', fareInr: 65000 },
      { month: 'Oct', fareInr: 63200 },
      { month: 'Nov', fareInr: 66900 },
      { month: 'Dec', fareInr: 84000 },
    ],
  },
];
